// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DbContext;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ExcuserContex))]
    [Migration("20191213093153_initial-data-seeding")]
    partial class initialdataseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Events"
                        },
                        new
                        {
                            Id = 3,
                            Name = "School"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Friends"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Excuse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<int>("SubcategoryId");

                    b.Property<int>("Tone");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Excuse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Hi%name%! It looks like I might be delayed. There is a traffic jam, it seems there are some construction workers on the way. I will be there as soon as this moves!",
                            SubcategoryId = 1,
                            Tone = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "I apologize for the inconvinience%name%, but I am unable to reach the time we have agreed. There seems to be a traffic jam ahead. I am unsure about how long will it take, but I will do my best to be with you as soon as I can. ",
                            SubcategoryId = 1,
                            Tone = 0
                        },
                        new
                        {
                            Id = 3,
                            Body = "Hey%name%! Sorry I’ll be a little late. I wasn’t expecting this but at home my roomies dog had fun with toilet paper and it is everywhere. I’ll take care of it and then meet you ASAP.",
                            SubcategoryId = 1,
                            Tone = 1
                        },
                        new
                        {
                            Id = 4,
                            Body = "Hello%name%! I apologise for being late. There was an urgent situation at home that need to be dealt with. Thank you for being patient with me and I’ll be there in 15 min.",
                            SubcategoryId = 1,
                            Tone = 0
                        },
                        new
                        {
                            Id = 5,
                            Body = "Hi%name%. I got carried away while watching the Gossip Girls yesterday. My alarm was not strong enough to wake me up, so I will be a little late for our meetup! Hope that's fine, I will pay for the coffee!",
                            SubcategoryId = 1,
                            Tone = 1
                        },
                        new
                        {
                            Id = 6,
                            Body = "Hello%name%! I have to apologize for being late for our meeting. I wasn't feeling well and over slept. I feel much better today, thank you!",
                            SubcategoryId = 1,
                            Tone = 0
                        },
                        new
                        {
                            Id = 7,
                            Body = "Hello%name%. My car broke down and I am trying to fix it. I am sorry for being late.",
                            SubcategoryId = 1,
                            Tone = 1
                        },
                        new
                        {
                            Id = 8,
                            Body = "Hi, I apologize for the inconvinience, but I am late, my car unfortunatelly broke down, I am waiting for the mechanic right now.",
                            SubcategoryId = 1,
                            Tone = 0
                        },
                        new
                        {
                            Id = 9,
                            Body = "Hi%name%! Thank you so much again for the invitation to the party, but I cannot attend. I am buried in books now, we have a deadline in school approaching in the subject I told you about. Thanks for understanding! ",
                            SubcategoryId = 2,
                            Tone = 1
                        },
                        new
                        {
                            Id = 10,
                            Body = "Hi%name%. I do apologize, but I will not be able to attend the party. It seems that the deadline in my school has fallen very close to the date and I will have to spend the time studying. This is very inconvinient and I know this is a last notice, but I cannot underestimate this subject. Thanks you for understanding the situation, I appreacitate that.",
                            SubcategoryId = 2,
                            Tone = 0
                        },
                        new
                        {
                            Id = 11,
                            Body = "Hey%name%! Thank you so much for the party invite but I won’t be able to attend. I have signed myself up for a workshop about pottery and wont be back in time. Have fun at the party.",
                            SubcategoryId = 2,
                            Tone = 1
                        },
                        new
                        {
                            Id = 12,
                            Body = "Hey%name%! Unfortunately, I won’t be able to join to the party. A while ago I signed myself up for a whole day workshop and since it is in Copenhagen I won’t make it back in time.",
                            SubcategoryId = 2,
                            Tone = 0
                        },
                        new
                        {
                            Id = 13,
                            Body = "Ola%name%! Thanks for having me but I gotta say no, my stomach viruses are basically destroying me from inside, so alcohol would make me no good. *sad emoji* Hope to see you soon! xoxo",
                            SubcategoryId = 2,
                            Tone = 1
                        },
                        new
                        {
                            Id = 14,
                            Body = "Hello%name%. I am very sorry to inform you I am not able to attend your party. I do sincerely thank you for the beautiful invitation, but I got a virus in my body that I need to cure in order to be able to live again. Thank you for your understanding.",
                            SubcategoryId = 2,
                            Tone = 0
                        },
                        new
                        {
                            Id = 15,
                            Body = "Hey%name%. I took the red pill my friend, now the dog I was left to take care of is glithing... Not coming to the party by the way... ",
                            SubcategoryId = 2,
                            Tone = 1
                        },
                        new
                        {
                            Id = 16,
                            Body = "Hello%name%. My friend left his dog with me for the day so I won't be able to make it to the party. ",
                            SubcategoryId = 2,
                            Tone = 0
                        },
                        new
                        {
                            Id = 17,
                            Body = "Oh%name%! This is so bad! My dog is throwing up and I cannot leave now, because I am scared it could get worse. I need to find some other day we will meet. ",
                            SubcategoryId = 3,
                            Tone = 1
                        },
                        new
                        {
                            Id = 18,
                            Body = "Hello%name%. I do apologize, but I cannot leave my dog alone at home today, it seems he ate something bad and I might need to take him to the vet later.",
                            SubcategoryId = 3,
                            Tone = 0
                        },
                        new
                        {
                            Id = 19,
                            Body = "Hi%name%! I sorry but yesterdays weather murdered me and I ended up catching a cold. So you wouldn’t get sick I think it would be better if I stayed home.",
                            SubcategoryId = 3,
                            Tone = 1
                        },
                        new
                        {
                            Id = 20,
                            Body = "Hey%name%! I apologise but I am unable to come over tonight. I think I caught a cold yesterday and it hasn’t past. I don’t want to infect anyone  so it would be better if I stayed home.",
                            SubcategoryId = 3,
                            Tone = 0
                        },
                        new
                        {
                            Id = 21,
                            Body = "Eh%name%, I just made myself some garlic bread and am planning on doing the laundry soon, do you mind if I take a raincheck tonight? Thx",
                            SubcategoryId = 3,
                            Tone = 1
                        },
                        new
                        {
                            Id = 22,
                            Body = "Hi%name%. I feel terribly sorry, but I have to cancel today. There is a stack of house chores that need to be done today. Let's reschedule, maybe next time at my place?",
                            SubcategoryId = 3,
                            Tone = 0
                        },
                        new
                        {
                            Id = 23,
                            Body = "Hey%name%. My damn hand is so swollen, it looks like a baloon. All from a tiger mosquito bite, I can't come over mate. ",
                            SubcategoryId = 3,
                            Tone = 1
                        },
                        new
                        {
                            Id = 24,
                            Body = "Hello%name%. I got bit by a tiger mosquito and my arm is incredibly swollen. I am going to my doctor now. I am sorry but I can't come over.",
                            SubcategoryId = 3,
                            Tone = 0
                        },
                        new
                        {
                            Id = 25,
                            Body = "Hey%name%! I was looking to the party so much, but I cannot make it after all! It seems there was a mistake in my calendar and it was not updated, and I did not see there is this conference which I signed up for last week. Can we reschedule?",
                            SubcategoryId = 4,
                            Tone = 1
                        },
                        new
                        {
                            Id = 26,
                            Body = "Hello%name%, I am so pleased by the invitation, which I really apprectiate. Regretably I cannot attend, as I would love to, because I am already booked at this date - there si a conference that I have promised I would attend.",
                            SubcategoryId = 4,
                            Tone = 0
                        },
                        new
                        {
                            Id = 27,
                            Body = "Hey%name%! I forgot that I need to go to school, so today won’t work for meeting up.I hope you aren’t annoyed.See you tomrorrow?",
                            SubcategoryId = 4,
                            Tone = 1
                        },
                        new
                        {
                            Id = 28,
                            Body = "Hello%name%. Unfortunately I won’t be able to meet up. I forgot that I have an appointment at school which I need to attend. I hope it wasn’t a big inconvenience. Thanks for being understanding and see you tomorrow!",
                            SubcategoryId = 4,
                            Tone = 0
                        },
                        new
                        {
                            Id = 29,
                            Body = "Gosh%name%, I am so retarded. I am keeping two calendars and I forgot to sync my other meetings. There is unfortunately a work meeting with a potential client, that I have to attend, so yeah. Fun stuff... hopefully next time?",
                            SubcategoryId = 4,
                            Tone = 1
                        },
                        new
                        {
                            Id = 30,
                            Body = "Hello%name%, unfortunately, I made an error in booking my meetings and I have another meeting at that time that I just have to attend. I would like to reschedule and offer you some more of our services for free. Thank you for being understanding and talk to you soon.",
                            SubcategoryId = 4,
                            Tone = 0
                        },
                        new
                        {
                            Id = 31,
                            Body = "I am sorry%name%, but I have had a migrena the whole day from the morning. I would love to reschedule, can we please get in touch when I am feeling better?",
                            SubcategoryId = 5,
                            Tone = 1
                        },
                        new
                        {
                            Id = 32,
                            Body = "Hello%name%, I was looking forward to meeting you, but unfortunatelly, I cannot come today due to enduring headache. I tried to take a headache pill, but it did not relieve my pain. I will be in touch about rescheduling our appointment. ",
                            SubcategoryId = 5,
                            Tone = 0
                        },
                        new
                        {
                            Id = 33,
                            Body = "Heya%name%! I won’t join you tonight with the party fun. I have had an insane week and I need to do nothing tonight. Say hi to the others from me though!",
                            SubcategoryId = 5,
                            Tone = 1
                        },
                        new
                        {
                            Id = 34,
                            Body = "I am sorry%name%, I know we were supposed to go out together tonight but I really don’t feel like doing anything. I need some time to myself tonight after this stressful week.",
                            SubcategoryId = 5,
                            Tone = 0
                        },
                        new
                        {
                            Id = 35,
                            Body = "Hey%name%, today is just a weird day and the weather got me really hard. Hope you won't mind me staying home and trying to fight with this season depression. I wouldn't be a great asset to your chill evening. Hope you understand... xoxo",
                            SubcategoryId = 5,
                            Tone = 1
                        },
                        new
                        {
                            Id = 36,
                            Body = "Hi%name%. I have to unfortunately skip today. I don't feel personally very well and I don't want to disrupt your cozy evening. I wish to meet some other time soon!",
                            SubcategoryId = 5,
                            Tone = 0
                        },
                        new
                        {
                            Id = 37,
                            Body = "Hi%name%! I am so sorry, but I cannot come to the party. I got a horrible headache and I am throwing up, it does not look like it is getting better anytime soon!",
                            SubcategoryId = 6,
                            Tone = 1
                        },
                        new
                        {
                            Id = 38,
                            Body = "Hello%name%. I do apologize for the inconviniance, but I will not be able to attend after all. I am experiencing a physical discomfort in my stomach and I know I could not be my full self on the party.",
                            SubcategoryId = 6,
                            Tone = 0
                        },
                        new
                        {
                            Id = 39,
                            Body = "Hey%name%, I know we were supposed to meet up but I went to the gym yesterday. and I am so sore I can’t move out of bed even. I would prefer to meet in the evening, can we do that?",
                            SubcategoryId = 6,
                            Tone = 1
                        },
                        new
                        {
                            Id = 40,
                            Body = "Hi%name%, I am sorry but I won’t make it to our meet-up in the morning. I went overboard in the gym and I need some recovery time. Do you mind if we postpone out meet-up to the morning?",
                            SubcategoryId = 6,
                            Tone = 0
                        },
                        new
                        {
                            Id = 41,
                            Body = "Hey%name%, I cannot come to our training today, because of a fracture of my bones. Could you tell the trainer I will write him later after I get better? Thanks!",
                            SubcategoryId = 6,
                            Tone = 0
                        },
                        new
                        {
                            Id = 42,
                            Body = "Hi%name%, I cannot come to this or few next trainings. I fractured some bones, at the moment I am still waiting for the results. I will let you know of my status as soon as possible. Thank you for understanding!",
                            SubcategoryId = 6,
                            Tone = 0
                        },
                        new
                        {
                            Id = 43,
                            Body = "Hi %name%! I believe I am so sorry, but I got cold from the weather. I will not be able to meet up today. I will text you later about some other plans we can do together. ",
                            SubcategoryId = 6,
                            Tone = 1
                        },
                        new
                        {
                            Id = 44,
                            Body = "Hi%name%, winter weather incredibly sick and I am unable to move my body without shivering or feeling pain. I am sorry but I can't make it to the reunion.",
                            SubcategoryId = 6,
                            Tone = 0
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.ExcuseKeyword", b =>
                {
                    b.Property<int>("ExcuseId");

                    b.Property<int>("KeywordId");

                    b.HasKey("ExcuseId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("ExcuseKeyword");

                    b.HasData(
                        new
                        {
                            ExcuseId = 1,
                            KeywordId = 1
                        },
                        new
                        {
                            ExcuseId = 2,
                            KeywordId = 1
                        },
                        new
                        {
                            ExcuseId = 1,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 2,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 3,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 4,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 5,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 6,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 1,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 2,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 3,
                            KeywordId = 4
                        },
                        new
                        {
                            ExcuseId = 4,
                            KeywordId = 4
                        },
                        new
                        {
                            ExcuseId = 3,
                            KeywordId = 5
                        },
                        new
                        {
                            ExcuseId = 4,
                            KeywordId = 5
                        },
                        new
                        {
                            ExcuseId = 4,
                            KeywordId = 6
                        },
                        new
                        {
                            ExcuseId = 5,
                            KeywordId = 6
                        },
                        new
                        {
                            ExcuseId = 5,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 6,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 7,
                            KeywordId = 8
                        },
                        new
                        {
                            ExcuseId = 7,
                            KeywordId = 9
                        },
                        new
                        {
                            ExcuseId = 7,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 8,
                            KeywordId = 8
                        },
                        new
                        {
                            ExcuseId = 8,
                            KeywordId = 9
                        },
                        new
                        {
                            ExcuseId = 8,
                            KeywordId = 2
                        },
                        new
                        {
                            ExcuseId = 9,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 9,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 9,
                            KeywordId = 11
                        },
                        new
                        {
                            ExcuseId = 10,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 10,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 10,
                            KeywordId = 11
                        },
                        new
                        {
                            ExcuseId = 11,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 11,
                            KeywordId = 12
                        },
                        new
                        {
                            ExcuseId = 11,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 12,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 12,
                            KeywordId = 12
                        },
                        new
                        {
                            ExcuseId = 12,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 13,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 13,
                            KeywordId = 13
                        },
                        new
                        {
                            ExcuseId = 13,
                            KeywordId = 14
                        },
                        new
                        {
                            ExcuseId = 14,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 14,
                            KeywordId = 13
                        },
                        new
                        {
                            ExcuseId = 14,
                            KeywordId = 14
                        },
                        new
                        {
                            ExcuseId = 15,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 15,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 15,
                            KeywordId = 15
                        },
                        new
                        {
                            ExcuseId = 16,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 16,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 16,
                            KeywordId = 15
                        },
                        new
                        {
                            ExcuseId = 17,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 17,
                            KeywordId = 15
                        },
                        new
                        {
                            ExcuseId = 17,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 18,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 18,
                            KeywordId = 15
                        },
                        new
                        {
                            ExcuseId = 18,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 19,
                            KeywordId = 16
                        },
                        new
                        {
                            ExcuseId = 19,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 19,
                            KeywordId = 18
                        },
                        new
                        {
                            ExcuseId = 20,
                            KeywordId = 16
                        },
                        new
                        {
                            ExcuseId = 20,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 20,
                            KeywordId = 18
                        },
                        new
                        {
                            ExcuseId = 21,
                            KeywordId = 19
                        },
                        new
                        {
                            ExcuseId = 21,
                            KeywordId = 20
                        },
                        new
                        {
                            ExcuseId = 21,
                            KeywordId = 16
                        },
                        new
                        {
                            ExcuseId = 22,
                            KeywordId = 19
                        },
                        new
                        {
                            ExcuseId = 22,
                            KeywordId = 20
                        },
                        new
                        {
                            ExcuseId = 22,
                            KeywordId = 16
                        },
                        new
                        {
                            ExcuseId = 23,
                            KeywordId = 21
                        },
                        new
                        {
                            ExcuseId = 23,
                            KeywordId = 22
                        },
                        new
                        {
                            ExcuseId = 23,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 24,
                            KeywordId = 21
                        },
                        new
                        {
                            ExcuseId = 24,
                            KeywordId = 22
                        },
                        new
                        {
                            ExcuseId = 24,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 25,
                            KeywordId = 12
                        },
                        new
                        {
                            ExcuseId = 25,
                            KeywordId = 23
                        },
                        new
                        {
                            ExcuseId = 25,
                            KeywordId = 24
                        },
                        new
                        {
                            ExcuseId = 26,
                            KeywordId = 12
                        },
                        new
                        {
                            ExcuseId = 26,
                            KeywordId = 23
                        },
                        new
                        {
                            ExcuseId = 26,
                            KeywordId = 24
                        },
                        new
                        {
                            ExcuseId = 27,
                            KeywordId = 25
                        },
                        new
                        {
                            ExcuseId = 27,
                            KeywordId = 26
                        },
                        new
                        {
                            ExcuseId = 27,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 28,
                            KeywordId = 25
                        },
                        new
                        {
                            ExcuseId = 28,
                            KeywordId = 26
                        },
                        new
                        {
                            ExcuseId = 28,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 29,
                            KeywordId = 27
                        },
                        new
                        {
                            ExcuseId = 29,
                            KeywordId = 28
                        },
                        new
                        {
                            ExcuseId = 29,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 30,
                            KeywordId = 27
                        },
                        new
                        {
                            ExcuseId = 30,
                            KeywordId = 28
                        },
                        new
                        {
                            ExcuseId = 30,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 31,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 31,
                            KeywordId = 29
                        },
                        new
                        {
                            ExcuseId = 31,
                            KeywordId = 30
                        },
                        new
                        {
                            ExcuseId = 32,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 32,
                            KeywordId = 29
                        },
                        new
                        {
                            ExcuseId = 32,
                            KeywordId = 30
                        },
                        new
                        {
                            ExcuseId = 33,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 33,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 33,
                            KeywordId = 31
                        },
                        new
                        {
                            ExcuseId = 34,
                            KeywordId = 10
                        },
                        new
                        {
                            ExcuseId = 34,
                            KeywordId = 3
                        },
                        new
                        {
                            ExcuseId = 34,
                            KeywordId = 31
                        },
                        new
                        {
                            ExcuseId = 35,
                            KeywordId = 33
                        },
                        new
                        {
                            ExcuseId = 35,
                            KeywordId = 32
                        },
                        new
                        {
                            ExcuseId = 35,
                            KeywordId = 34
                        },
                        new
                        {
                            ExcuseId = 36,
                            KeywordId = 32
                        },
                        new
                        {
                            ExcuseId = 36,
                            KeywordId = 33
                        },
                        new
                        {
                            ExcuseId = 36,
                            KeywordId = 34
                        },
                        new
                        {
                            ExcuseId = 37,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 37,
                            KeywordId = 30
                        },
                        new
                        {
                            ExcuseId = 37,
                            KeywordId = 23
                        },
                        new
                        {
                            ExcuseId = 38,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 38,
                            KeywordId = 30
                        },
                        new
                        {
                            ExcuseId = 38,
                            KeywordId = 23
                        },
                        new
                        {
                            ExcuseId = 39,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 39,
                            KeywordId = 34
                        },
                        new
                        {
                            ExcuseId = 39,
                            KeywordId = 31
                        },
                        new
                        {
                            ExcuseId = 40,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 40,
                            KeywordId = 34
                        },
                        new
                        {
                            ExcuseId = 40,
                            KeywordId = 31
                        },
                        new
                        {
                            ExcuseId = 41,
                            KeywordId = 22
                        },
                        new
                        {
                            ExcuseId = 41,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 41,
                            KeywordId = 5
                        },
                        new
                        {
                            ExcuseId = 42,
                            KeywordId = 22
                        },
                        new
                        {
                            ExcuseId = 42,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 42,
                            KeywordId = 5
                        },
                        new
                        {
                            ExcuseId = 43,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 43,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 43,
                            KeywordId = 18
                        },
                        new
                        {
                            ExcuseId = 44,
                            KeywordId = 7
                        },
                        new
                        {
                            ExcuseId = 44,
                            KeywordId = 17
                        },
                        new
                        {
                            ExcuseId = 44,
                            KeywordId = 18
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Keyword");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "traffic"
                        },
                        new
                        {
                            Id = 2,
                            Value = "late"
                        },
                        new
                        {
                            Id = 3,
                            Value = "friend"
                        },
                        new
                        {
                            Id = 4,
                            Value = "home"
                        },
                        new
                        {
                            Id = 5,
                            Value = "accident"
                        },
                        new
                        {
                            Id = 6,
                            Value = "movies"
                        },
                        new
                        {
                            Id = 7,
                            Value = "meeting"
                        },
                        new
                        {
                            Id = 8,
                            Value = "car"
                        },
                        new
                        {
                            Id = 9,
                            Value = "malfunction"
                        },
                        new
                        {
                            Id = 10,
                            Value = "party"
                        },
                        new
                        {
                            Id = 11,
                            Value = "studying"
                        },
                        new
                        {
                            Id = 12,
                            Value = "doublebooking"
                        },
                        new
                        {
                            Id = 13,
                            Value = "illness"
                        },
                        new
                        {
                            Id = 14,
                            Value = "virus"
                        },
                        new
                        {
                            Id = 15,
                            Value = "pet"
                        },
                        new
                        {
                            Id = 16,
                            Value = "chill"
                        },
                        new
                        {
                            Id = 17,
                            Value = "sick"
                        },
                        new
                        {
                            Id = 18,
                            Value = "cold"
                        },
                        new
                        {
                            Id = 19,
                            Value = "food"
                        },
                        new
                        {
                            Id = 20,
                            Value = "laundry"
                        },
                        new
                        {
                            Id = 21,
                            Value = "allergy"
                        },
                        new
                        {
                            Id = 22,
                            Value = "pain"
                        },
                        new
                        {
                            Id = 23,
                            Value = "polite"
                        },
                        new
                        {
                            Id = 24,
                            Value = "schedule"
                        },
                        new
                        {
                            Id = 25,
                            Value = "school"
                        },
                        new
                        {
                            Id = 26,
                            Value = "appointment"
                        },
                        new
                        {
                            Id = 27,
                            Value = "work"
                        },
                        new
                        {
                            Id = 28,
                            Value = "sync"
                        },
                        new
                        {
                            Id = 29,
                            Value = "headache"
                        },
                        new
                        {
                            Id = 30,
                            Value = "hangover"
                        },
                        new
                        {
                            Id = 31,
                            Value = "lazy"
                        },
                        new
                        {
                            Id = 32,
                            Value = "season"
                        },
                        new
                        {
                            Id = 33,
                            Value = "depression"
                        },
                        new
                        {
                            Id = 34,
                            Value = "friend"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategory");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Late for work"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Physical"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Family problems"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Lazy"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Physical"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Transportation "
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Late for class"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Working"
                        },
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Name = "Late for meetup"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Name = "Not attending party"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Name = "Not coming over "
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Name = "Doublebooking "
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Name = "Not feeling like it "
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Name = "Physical "
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Excuse", b =>
                {
                    b.HasOne("WebApplication1.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication1.Models.ExcuseKeyword", b =>
                {
                    b.HasOne("WebApplication1.Models.Excuse", "Excuse")
                        .WithMany("ExcuseKeywords")
                        .HasForeignKey("ExcuseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApplication1.Models.Keyword", "Keyword")
                        .WithMany("ExcuseKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication1.Models.Subcategory", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
